services:
  book-mcp-server:
    container_name: book-mcp-server
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=PRODUCTION
    restart: unless-stopped 