version: '3.8'

services:
  # MCP Server Service
  mcp-server:
    container_name: mcp-server
    build:
      context: .
      target: builder  # Build using the builder stage
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./faiss_index:/app/faiss_index
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - ENV=${ENV:-PRODUCTION}
      - PYTHONPATH=/app
      # RAG-specific variables
      - INDEX_DIRECTORY=/app/faiss_index
      # Force HTTP transport
      - MCP_TRANSPORT=http
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    command: python start_server.py

  # Uncomment and configure additional services as needed
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# Define volumes for persistent data
# volumes:
#   redis_data: