
book:
  title: "Competitive Strategy"
  author: "Michael Porter"
  domain: "strategy"
  description: "Techniques d'analyse des industries et de la concurrence"
  version: "1.0"

concepts:
  - name: "Five Forces"
    description: "Modèle d'analyse de l'attractivité d'une industrie basé sur 5 forces concurrentielles"
    prerequisites: []
    related_concepts: ["Competitive Advantage", "Industry Analysis"]
  
  - name: "Generic Strategies"
    description: "Trois stratégies génériques: cost leadership, differentiation, focus"
    prerequisites: ["Five Forces"]
    related_concepts: ["Value Chain"]
  
  - name: "Value Chain"
    description: "Analyse des activités créatrices de valeur dans l'entreprise"
    prerequisites: []
    related_concepts: ["Generic Strategies"]

methods:
  - name: "Industry Analysis"
    description: "Analyse complète d'une industrie selon le modèle des 5 forces de Porter"
    concepts_used: ["Five Forces"]
    input_schema:
      industry_name:
        type: "string"
        description: "Nom de l'industrie à analyser"
      company_context:
        type: "string"
        description: "Contexte de l'entreprise (taille, position, etc.)"
      market_data:
        type: "string"
        description: "Données de marché disponibles"
    prompt_template: |
      Réalise une analyse complète de l'industrie "{industry_name}" en appliquant le modèle des 5 forces de Porter.
      
      Contexte de l'entreprise: {company_context}
      Données de marché: {market_data}
      
      Pour chaque force, analyse:
      1. **Menace des nouveaux entrants**
      2. **Pouvoir de négociation des fournisseurs**  
      3. **Pouvoir de négociation des clients**
      4. **Menace des produits de substitution**
      5. **Intensité de la rivalité concurrentielle**
      
      Conclus par une évaluation de l'attractivité de l'industrie et des implications stratégiques.
    examples:
      - industry: "Streaming vidéo"
        context: "Startup technologique"
        expected_output: "Analyse détaillée avec recommandations"
  
  - name: "Competitive Positioning"
    description: "Définit le positionnement concurrentiel optimal selon les stratégies génériques"
    concepts_used: ["Generic Strategies", "Value Chain"]
    input_schema:
      company_profile:
        type: "string"
        description: "Profil détaillé de l'entreprise"
      competitors_info:
        type: "string"
        description: "Informations sur les principaux concurrents"
      resources_capabilities:
        type: "string"
        description: "Ressources et capacités de l'entreprise"
    prompt_template: |
      Détermine la stratégie générique optimale pour cette entreprise selon Porter.
      
      Profil de l'entreprise: {company_profile}
      Concurrents: {competitors_info}
      Ressources et capacités: {resources_capabilities}
      
      Analyse:
      1. **Faisabilité de la stratégie de coût (Cost Leadership)**
      2. **Faisabilité de la stratégie de différenciation**
      3. **Opportunités de stratégie de niche (Focus)**
      
      Recommande la stratégie la plus appropriée avec justification détaillée.

custom_instructions: |
  Tu es un expert en stratégie d'entreprise formé selon les méthodes de Michael Porter.
  Applique rigoureusement les frameworks théoriques tout en restant pratique et actionnable.
  Cite toujours les concepts du livre et explique leur application dans le contexte donné.
